### ISSUE TITLE
Change TopicService namespace for Newscoop 4.4

### ISSUE THREAD

**Issue by takeit** [newscoop/plugin-SolrSearchPluginBundle#5]
In Newscoop 4.4+  in `SolrQueryService` we need to use: `Newscoop\NewscoopBundle\Services\TopicService;` instead of `Newscoop\Topic\TopicService;

Please, create plugin tag for Newscoop 4.3 and adjust changes.

**Comment by m038** [comment]
Check the branch https://github.com/newscoop/plugin-SolrSearchPluginBundle/tree/master_4.4 

It already contains those fixes.

**Comment by takeit** [comment]
great, thanks
